version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  video-preview:
    lang: python3-http
    build_args:
      ADDITIONAL_PACKAGE: "ffmpeg"
    handler: ./video-preview
    image: welteki/video-preview:0.0.2
    environment:
      debug: false
      write_timeout: 10m2s
      read_timeout: 10m2s
      exec_timeout: 10m
    environment_file:
      - ./s3_config.yaml
    secrets:
      - video-preview-s3-key
      - video-preview-s3-secret

# Run
# faas-cli template pull stack
configuration:
  templates:
    - name: python3-http